import type {
  Advocate,
  DocumentCategoryMeta,
  LegalDocument,
  LegalRequest,
  Testimonial,
  Specialty,
  Region,
} from "./types";

// ============================================================================
// SPECIALTIES & REGIONS LOOKUPS
// ============================================================================

export const SPECIALTIES: Record<Specialty, { uz: string; ru: string; icon: string }> = {
  family: { uz: "Oilaviy huquq", ru: "Семейное право", icon: "Users" },
  criminal: { uz: "Jinoyat huquqi", ru: "Уголовное право", icon: "ShieldAlert" },
  civil: { uz: "Fuqarolik huquqi", ru: "Гражданское право", icon: "Scale" },
  corporate: { uz: "Korporativ huquq", ru: "Корпоративное право", icon: "Building2" },
  tax: { uz: "Soliq huquqi", ru: "Налоговое право", icon: "Receipt" },
  labor: { uz: "Mehnat huquqi", ru: "Трудовое право", icon: "Briefcase" },
  "real-estate": { uz: "Ko'chmas mulk huquqi", ru: "Недвижимость", icon: "Home" },
  intellectual: { uz: "Intellektual mulk huquqi", ru: "Интеллектуальная собственность", icon: "Lightbulb" },
  administrative: { uz: "Ma'muriy huquq", ru: "Административное право", icon: "FileText" },
  international: { uz: "Xalqaro huquq", ru: "Международное право", icon: "Globe" },
};

export const REGIONS: Record<Region, { uz: string; ru: string }> = {
  "tashkent-city": { uz: "Toshkent shahri", ru: "город Ташкент" },
  "tashkent-region": { uz: "Toshkent viloyati", ru: "Ташкентская область" },
  samarkand: { uz: "Samarqand viloyati", ru: "Самаркандская область" },
  bukhara: { uz: "Buxoro viloyati", ru: "Бухарская область" },
  andijan: { uz: "Andijon viloyati", ru: "Андижанская область" },
  fergana: { uz: "Farg'ona viloyati", ru: "Ферганская область" },
  namangan: { uz: "Namangan viloyati", ru: "Наманганская область" },
  kashkadarya: { uz: "Qashqadaryo viloyati", ru: "Кашкадарьинская область" },
  surkhandarya: { uz: "Surxondaryo viloyati", ru: "Сурхандарьинская область" },
  navoi: { uz: "Navoiy viloyati", ru: "Навоийская область" },
  jizzakh: { uz: "Jizzax viloyati", ru: "Джизакская область" },
  sirdarya: { uz: "Sirdaryo viloyati", ru: "Сырдарьинская область" },
  khorezm: { uz: "Xorazm viloyati", ru: "Хорезмская область" },
  karakalpakstan: { uz: "Qoraqalpog'iston Respublikasi", ru: "Республика Каракалпакстан" },
};

// ============================================================================
// DOCUMENT CATEGORIES (inspired by yurxizmat.uz)
// ============================================================================

export const DOCUMENT_CATEGORIES: DocumentCategoryMeta[] = [
  {
    id: "contracts",
    nameUz: "Shartnomalar",
    nameRu: "Договоры",
    nameEn: "Contracts",
    descriptionUz: "Yuridik shaxslarga, ko'chmas mulkka, avtotransportlarga oid shartnomalar",
    icon: "FileSignature",
    color: "emerald",
    count: 248,
    subcategories: [
      "Yuridik shaxslarga oid",
      "Ko'chmas mulkka oid",
      "Avtotransportlarga oid",
      "Xizmat ko'rsatishga oid",
      "Oldi-sotdi",
      "Ijara",
    ],
  },
  {
    id: "applications",
    nameUz: "Arizalar",
    nameRu: "Заявления",
    nameEn: "Applications",
    descriptionUz: "Yuridik va jismoniy shaxslar, bolalar uchun ariza namunalari",
    icon: "FileText",
    color: "amber",
    count: 132,
    subcategories: [
      "Yuridik shaxslarga oid",
      "Jismoniy shaxslarga oid",
      "Bolalar uchun",
      "Davlat organlariga",
      "Ta'til va nafaqa",
    ],
  },
  {
    id: "personal",
    nameUz: "Shaxsiy tarkibga oid hujjatlar",
    nameRu: "Кадровые документы",
    nameEn: "Personal Records",
    descriptionUz: "Arizalar, bildirgilar, buyruqlar va ish bilan bog'liq hujjatlar",
    icon: "UserCheck",
    color: "rose",
    count: 86,
    subcategories: ["Arizalar", "Bildirgilar", "Buyruqlar", "Ishga qabul", "Ishdan bo'shash"],
  },
  {
    id: "notarial",
    nameUz: "Notarial tasdiqlanadigan hujjatlar",
    nameRu: "Нотариальные документы",
    nameEn: "Notarial",
    descriptionUz: "Arizalar, vasiyatnomalar, ishonchnomalar va boshqa notarial hujjatlar",
    icon: "Stamp",
    color: "violet",
    count: 64,
    subcategories: ["Arizalar", "Vasiyatnomalar", "Ishonchnomalar", "Vorisiyat", "Vakolatnomalar"],
  },
  {
    id: "court",
    nameUz: "Sudga oid hujjatlar",
    nameRu: "Судебные документы",
    nameEn: "Court Documents",
    descriptionUz: "Da'vo arizalari, apellyatsiya va kassatsiya shikoyatlari",
    icon: "Gavel",
    color: "sky",
    count: 95,
    subcategories: [
      "Da'vo arizalari",
      "Apellyatsiya shikoyatlari",
      "Kassatsiya shikoyatlari",
      "Ijro hujjatlari",
      "Moderator qarorlari",
    ],
  },
  {
    id: "corporate",
    nameUz: "Korporativ hujjatlar",
    nameRu: "Корпоративные документы",
    nameEn: "Corporate",
    descriptionUz: "Talabnomalar, ustavlar, dalolatnomalar va bayonnomalar",
    icon: "Building2",
    color: "teal",
    count: 72,
    subcategories: ["Talabnomalar", "Ustavlar", "Dalolatnomalar", "Bayonnomalar", "Qarorlar"],
  },
];

// ============================================================================
// LEGAL DOCUMENTS (mix of yurxizmat-style templates)
// ============================================================================

export const LEGAL_DOCUMENTS: LegalDocument[] = [
  {
    id: "doc-001",
    slug: "mehnat-shartnomasi",
    titleUz: "Mehnat shartnomasi (kontrakt)",
    titleRu: "Трудовой договор (контракт)",
    category: "contracts",
    subcategory: "Xizmat ko'rsatishga oid",
    descriptionUz:
      "Xodim va ish beruvchi o'rtasidagi standart mehnat shartnomasi namunasi. Ish haqi, ish vaqti, ta'til va tomonlar javobgarligi to'liq tartibga solingan. O'zbekiston Mehnat kodeksiga muvofiq tayyorlangan.",
    descriptionRu:
      "Стандартный образец трудового договора между работником и работодателем. Полностью соответствует Трудовому кодексу Республики Узбекистан.",
    pages: 6,
    downloads: 18432,
    rating: 4.9,
    priceUzs: 0,
    isFree: true,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx", "online"],
    fieldsCount: 18,
    estimatedFillMinutes: 12,
    legalBasisUz: "O'zR Mehnat kodeksi, 70-moddaga muvofiq",
    lastUpdated: "2026-06-12",
    tags: ["mehnat", "shartnoma", "kontrakt", "ish beruvchi"],
  },
  {
    id: "doc-002",
    slug: "oldi-sotdi-shartnomasi",
    titleUz: "Oldi-sotdi shartnomasi",
    titleRu: "Договор купли-продажи",
    category: "contracts",
    subcategory: "Oldi-sotdi",
    descriptionUz:
      "Tovar yoki mulkni sotib olish-sotish bo'yicha universal shartnoma. To'lov tartibi, yetkazib berish muddati, kafolat va javobgarlik shartlari aniq belgilangan.",
    descriptionRu: "Универсальный договор купли-продажи имущества или товаров.",
    pages: 5,
    downloads: 15238,
    rating: 4.8,
    priceUzs: 25000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx", "online"],
    fieldsCount: 14,
    estimatedFillMinutes: 10,
    legalBasisUz: "O'zR Fuqarolik kodeksi, 367-modda",
    lastUpdated: "2026-05-28",
    tags: ["oldi-sotdi", "shartnoma", "mulk"],
  },
  {
    id: "doc-003",
    slug: "ijara-shartnomasi",
    titleUz: "Ijara shartnomasi",
    titleRu: "Договор аренды",
    category: "contracts",
    subcategory: "Ijara",
    descriptionUz:
      "Ko'chmas mulk (kvartira, ofis, do'kon) ijaraga berish uchun professional shartnoma namunasi. Ijara to'lovi, kommunal xizmatlar, ta'mirlash va bekor qilish shartlari mavjud.",
    descriptionRu: "Профессиональный договор аренды недвижимого имущества.",
    pages: 7,
    downloads: 12764,
    rating: 4.7,
    priceUzs: 35000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx", "online"],
    fieldsCount: 22,
    estimatedFillMinutes: 15,
    legalBasisUz: "O'zR Fuqarolik kodeksi, 542-modda",
    lastUpdated: "2026-06-03",
    tags: ["ijara", "kvartira", "ko'chmas mulk"],
  },
  {
    id: "doc-004",
    slug: "ajrashish-davo-arizasi",
    titleUz: "Nikohdan ajratish haqida da'vo arizasi",
    titleRu: "Исковое заявление о расторжении брака",
    category: "court",
    subcategory: "Da'vo arizalari",
    descriptionUz:
      "Sudga nikohni bekor qilish to'g'risida beriladigan da'vo arizasi namunasi. Bolalar va umumiy mulk masalalari ko'rib chiqilgan variantda tayyor. Sudga taqdim etishga tayyor.",
    descriptionRu: "Образец искового заявления о расторжении брака, подаваемого в суд.",
    pages: 4,
    downloads: 11092,
    rating: 4.8,
    priceUzs: 40000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx"],
    fieldsCount: 11,
    estimatedFillMinutes: 18,
    legalBasisUz: "O'zR Oila kodeksi, 41-modda",
    lastUpdated: "2026-04-19",
    tags: ["oilaviy", "ajrashish", "da'vo", "sud"],
  },
  {
    id: "doc-005",
    slug: "avto-ijara-shartnomasi",
    titleUz: "Transport vositasining ijara shartnomasi",
    titleRu: "Договор аренды транспортного средства",
    category: "contracts",
    subcategory: "Avtotransportlarga oid",
    descriptionUz:
      "Avtomobil va boshqa transport vositalarini ijaraga berish uchun ixtisoslashtirilgan shartnoma. Sug'urta, texnik xizmat va javobgarlik to'liq qamrab olingan.",
    descriptionRu: "Специализированный договор аренды транспортного средства.",
    pages: 8,
    downloads: 8741,
    rating: 4.6,
    priceUzs: 30000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx", "online"],
    fieldsCount: 26,
    estimatedFillMinutes: 20,
    legalBasisUz: "O'zR Fuqarolik kodeksi, 542, 595-moddalar",
    lastUpdated: "2026-05-15",
    tags: ["avto", "ijara", "transport", "sug'urta"],
  },
  {
    id: "doc-006",
    slug: "xizmatlar-shartnomasi",
    titleUz: "Xizmatlar ko'rsatish (ishlarni bajarish) shartnomasi",
    titleRu: "Договор оказания услуг (выполнения работ)",
    category: "contracts",
    subcategory: "Xizmat ko'rsatishga oid",
    descriptionUz:
      "Xizmat ko'rsatuvchi va buyurtmachi o'rtasidagi shartnoma. Ish tartibi, muddatlar, sifat kafolati va to'lov shartlari aniq ko'rsatilgan. Kichik biznes uchun ideal.",
    descriptionRu: "Договор между исполнителем и заказчиком на оказание услуг.",
    pages: 5,
    downloads: 7632,
    rating: 4.7,
    priceUzs: 28000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx", "online"],
    fieldsCount: 16,
    estimatedFillMinutes: 14,
    legalBasisUz: "O'zR Fuqarolik kodeksi, 651-modda",
    lastUpdated: "2026-06-08",
    tags: ["xizmat", "shartnoma", "kichik biznes"],
  },
  {
    id: "doc-007",
    slug: "topshirish-qabul-qilish-dalolatnomasi",
    titleUz: "Tovar moddiy boyliklarni topshirish va qabul qilish dalolatnomasi",
    titleRu: "Акт приёма-передачи товарно-материальных ценностей",
    category: "corporate",
    subcategory: "Dalolatnomalar",
    descriptionUz:
      "Tovar yoki uskunalarni topshirish-qabul qilish bo'yicha rasmiy dalolatnoma. Inventarizatsiya, sifat tekshiruvi va javobgarlikni o'tkazish uchun standart forma.",
    descriptionRu: "Официальный акт приёма-передачи товарно-материальных ценностей.",
    pages: 3,
    downloads: 6912,
    rating: 4.5,
    priceUzs: 15000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx"],
    fieldsCount: 12,
    estimatedFillMinutes: 8,
    legalBasisUz: "O'zR Fuqarolik kodeksi, 374-modda",
    lastUpdated: "2026-05-22",
    tags: ["dalolatnoma", "topshirish", "qabul qilish", "uskuna"],
  },
  {
    id: "doc-008",
    slug: "moddiy-javobgarlik-shartnomasi",
    titleUz: "Moddiy javobgarlik shartnomasi",
    titleRu: "Договор о материальной ответственности",
    category: "personal",
    subcategory: "Ishga qabul",
    descriptionUz:
      "Xodimning to'liq moddiy javobgarligi to'g'risidagi shartnoma. Mol-mulk yo'qolishi yoki shikastlanishi holatlarida javobgarlik chegaralari aniq belgilangan.",
    descriptionRu: "Договор о полной материальной ответственности работника.",
    pages: 4,
    downloads: 5847,
    rating: 4.6,
    priceUzs: 20000,
    isFree: false,
    isPopular: true,
    isNew: false,
    formats: ["pdf", "docx"],
    fieldsCount: 9,
    estimatedFillMinutes: 6,
    legalBasisUz: "O'zR Mehnat kodeksi, 169-175-moddalar",
    lastUpdated: "2026-04-30",
    tags: ["moddiy", "javobgarlik", "mehnat", "xodim"],
  },
  {
    id: "doc-009",
    slug: "farzandlikka-olish-arizasi",
    titleUz: "Farzandlikka olish to'g'risida ariza",
    titleRu: "Заявление об усыновлении",
    category: "applications",
    subcategory: "Bolalar uchun",
    descriptionUz:
      "Farzandlikka olish (asrab olish) uchun rasmiy ariza namunasi. Vasiylik organi va sudga taqdim etish uchun to'liq tayyor. Hujjat talablari ro'yxati ilova qilingan.",
    descriptionRu: "Официальный образец заявления об усыновлении.",
    pages: 3,
    downloads: 2104,
    rating: 4.9,
    priceUzs: 0,
    isFree: true,
    isPopular: false,
    isNew: true,
    formats: ["pdf", "docx"],
    fieldsCount: 7,
    estimatedFillMinutes: 10,
    legalBasisUz: "O'zR Oila kodeksi, 90-modda",
    lastUpdated: "2026-07-01",
    tags: ["farzandlikka olish", "ariza", "oila", "bolalar"],
  },
  {
    id: "doc-010",
    slug: "otalikni-belgilash-arizasi",
    titleUz: "Otaliqni belgilash to'g'risida ariza",
    titleRu: "Заявление об установлении отцовства",
    category: "applications",
    subcategory: "Bolalar uchun",
    descriptionUz:
      "Fuqarolik holati dalolatnomalari (ZAGS) organiga otaliqni belgilash to'g'risida beriladigan ariza. Ona va ota tomonidan birgalikda beriladigan variant.",
    descriptionRu: "Заявление об установлении отцовства в органы ЗАГС.",
    pages: 2,
    downloads: 1876,
    rating: 4.7,
    priceUzs: 0,
    isFree: true,
    isPopular: false,
    isNew: true,
    formats: ["pdf", "docx"],
    fieldsCount: 6,
    estimatedFillMinutes: 7,
    legalBasisUz: "O'zR Oila kodeksi, 48-modda",
    lastUpdated: "2026-07-05",
    tags: ["otaliq", "ariza", "oila", "ZAGS"],
  },
  {
    id: "doc-011",
    slug: "mehnat-huquqlarini-tiklash",
    titleUz: "Mehnat huquqlarini tiklash bo'yicha da'vo arizasi",
    titleRu: "Исковое заявление о восстановлении трудовых прав",
    category: "court",
    subcategory: "Da'vo arizalari",
    descriptionUz:
      "Noto'g'ri ishdan haydalgan yoki mehnat huquqlari buzilgan xodimning tiklash to'g'risidagi da'vo arizasi. Mehnat nizolari komissiyasi yoki sudga taqdim etish uchun.",
    descriptionRu: "Исковое заявление о восстановлении нарушенных трудовых прав работника.",
    pages: 5,
    downloads: 3214,
    rating: 4.8,
    priceUzs: 45000,
    isFree: false,
    isPopular: false,
    isNew: true,
    formats: ["pdf", "docx"],
    fieldsCount: 13,
    estimatedFillMinutes: 20,
    legalBasisUz: "O'zR Mehnat kodeksi, 211-modda",
    lastUpdated: "2026-07-10",
    tags: ["mehnat", "tiklash", "da'vo", "sud"],
  },
  {
    id: "doc-012",
    slug: "toliq-muomalaga-layoqatli",
    titleUz: "To'liq muomalaga layoqatli deb topish haqida ariza",
    titleRu: "Заявление о признании дееспособным",
    category: "applications",
    subcategory: "Jismoniy shaxslarga oid",
    descriptionUz:
      "Voyaga yetmagan shaxsni to'liq muomala layoqatli deb tan olish to'g'risida ariza. 16 yoshga to'lib, ishga joylashgan yoki uylangan shaxslar uchun sudga beriladi.",
    descriptionRu: "Заявление о признании несовершеннолетнего полностью дееспособным.",
    pages: 2,
    downloads: 1456,
    rating: 4.6,
    priceUzs: 0,
    isFree: true,
    isPopular: false,
    isNew: true,
    formats: ["pdf", "docx"],
    fieldsCount: 5,
    estimatedFillMinutes: 6,
    legalBasisUz: "O'zR Fuqarolik kodeksi, 26-modda",
    lastUpdated: "2026-07-12",
    tags: ["muomala layoqati", "ariza", "voyaga yetmagan"],
  },
];

// ============================================================================
// ADVOCATES (hh.uz-style candidate cards)
// ============================================================================

export const ADVOCATES: Advocate[] = [
  {
    id: "adv-001",
    slug: "akmal-rashidov",
    name: "Akmal Rashidov",
    photo: "https://i.pravatar.cc/300?img=12",
    titleUz: "Senior advokat, Oilaviy huquq bo'yicha mutaxassis",
    titleRu: "Старший адвокат, специалист по семейному праву",
    specialty: "family",
    secondarySpecialties: ["civil", "real-estate"],
    region: "tashkent-city",
    city: "Toshkent",
    experienceYears: 14,
    licenseNumber: "ADV-2011-0438",
    rating: 4.9,
    reviewsCount: 287,
    casesResolved: 412,
    responseTimeHours: 1,
    consultationFee: { amount: 150000, currency: "UZS" },
    hourlyFee: { amount: 500000, currency: "UZS" },
    languages: ["uz", "ru", "en"],
    verified: true,
    topRated: true,
    online: true,
    bioUz:
      "14 yillik tajribaga ega oilaviy huquq bo'yicha yetakchi advokat. 400 dan ortiq ajrashish, bolalar bilan aloqada bo'lish, aliment va bo'linish ishlarini muvaffaqiyatli yakunlagan. Toshkent Davlat Yuridik Universitetini imtiyozli diplom bilan tugatgan.",
    bioRu:
      "Ведущий адвокат по семейному праву с 14-летним опытом. Успешно завершил более 400 дел о разводе, взыскании алиментов и разделе имущества.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Toshkent Davlat Yuridik Universiteti", year: 2010 },
      { degree: "Yuridik fanlar magistri", institution: "Toshkent Davlat Yuridik Universiteti", year: 2012 },
    ],
    expertise: ["Ajralish protsedurasi", "Aliment undirish", "Mulk bo'linishi", "Bolalar bilan aloqada bo'lish", "Nikoh shartnomasi"],
    successRate: 92,
    availability: "available",
    tags: ["oilaviy", "ajrashish", "aliment", "TOP-10"],
  },
  {
    id: "adv-002",
    slug: "malika-karimova",
    name: "Malika Karimova",
    photo: "https://i.pravatar.cc/300?img=45",
    titleUz: "Korporativ huquq va soliq bo'yicha ekspert",
    titleRu: "Эксперт по корпоративному и налоговому праву",
    specialty: "corporate",
    secondarySpecialties: ["tax", "labor"],
    region: "tashkent-city",
    city: "Toshkent",
    experienceYears: 11,
    licenseNumber: "ADV-2014-0612",
    rating: 4.8,
    reviewsCount: 198,
    casesResolved: 312,
    responseTimeHours: 2,
    consultationFee: { amount: 250000, currency: "UZS" },
    hourlyFee: { amount: 800000, currency: "UZS" },
    languages: ["uz", "ru", "en"],
    verified: true,
    topRated: true,
    online: true,
    bioUz:
      "Korporativ huquq bo'yicha yirik ekspert. 100 dan ortiq MChJ va AJ larni ro'yxatdan o'tkazish, qayta tashkil etish va tugatish ishlarini bajargan. Xorijiy investorlar uchun konsalting xizmatlarini ko'rsatadi. Big Four auditor kompaniyasida 4 yil ishlagan.",
    bioRu: "Крупный эксперт по корпоративному праву. Более 100 регистраций и ликвидаций компаний.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Toshkent Davlat Yuridik Universiteti", year: 2012 },
      { degree: "MBA", institution: "Westminster International University", year: 2015 },
    ],
    expertise: ["MChJ ro'yxatga olish", "Soliq optimallashtirish", "Aksiyadorlar shartnomasi", "Audyat", "M&A bitimlari"],
    successRate: 89,
    availability: "available",
    tags: ["korporativ", "soliq", "MChJ", "TOP-10"],
  },
  {
    id: "adv-003",
    slug: "bobur-yuldashev",
    name: "Bobur Yo'ldoshev",
    photo: "https://i.pravatar.cc/300?img=33",
    titleUz: "Jinoyat ishlari bo'yicha advokat",
    titleRu: "Адвокат по уголовным делам",
    specialty: "criminal",
    secondarySpecialties: ["administrative"],
    region: "samarkand",
    city: "Samarqand",
    experienceYears: 18,
    licenseNumber: "ADV-2007-0156",
    rating: 4.9,
    reviewsCount: 421,
    casesResolved: 587,
    responseTimeHours: 1,
    consultationFee: { amount: 300000, currency: "UZS" },
    hourlyFee: { amount: 1200000, currency: "UZS" },
    languages: ["uz", "ru"],
    verified: true,
    topRated: true,
    online: false,
    bioUz:
      "18 yillik tajribaga ega jinoyat ishlari bo'yicha yetakchi advokat. Jinoyat kodeksining og'ir va og'ir bo'lmagan moddalari bo'yicha 500 dan ortiq ishni himoya qilgan. O'lim jazosini olib tashlash, hukmni yumshatish va reabilitatsiya ishlarida katta muvaffaqiyatga erishgan.",
    bioRu: "Ведущий адвокат по уголовным делам с 18-летним опытом. Более 500 успешно защищённых дел.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Samarqand Davlat Universiteti", year: 2006 },
      { degree: "Yuridik fanlar nomzodi", institution: "O'zR Fanlar Akademiyasi", year: 2011 },
    ],
    expertise: ["Jinoyat ishlari himoyasi", "Hibsga olish qarorini shikoyat qilish", "Reabilitatsiya", "Tergov ishlari", "Apellyatsiya"],
    successRate: 87,
    availability: "busy",
    tags: ["jinoyat", "himoya", "sud", "TOP-10"],
  },
  {
    id: "adv-004",
    slug: "dilnoza-ahmedova",
    name: "Dilnoza Ahmedova",
    photo: "https://i.pravatar.cc/300?img=44",
    titleUz: "Ko'chmas mulk va fuqarolik huquqi bo'yicha advokat",
    titleRu: "Адвокат по недвижимости и гражданскому праву",
    specialty: "real-estate",
    secondarySpecialties: ["civil", "corporate"],
    region: "tashkent-region",
    city: "Toshkent viloyati",
    experienceYears: 9,
    licenseNumber: "ADV-2016-0891",
    rating: 4.7,
    reviewsCount: 156,
    casesResolved: 234,
    responseTimeHours: 3,
    consultationFee: { amount: 200000, currency: "UZS" },
    hourlyFee: { amount: 650000, currency: "UZS" },
    languages: ["uz", "ru", "en"],
    verified: true,
    topRated: false,
    online: true,
    bioUz:
      "Ko'chmas mulk bitimlarini yuridik qo'llab-quvvatlash bo'yicha mutaxassis. Yer uchastkalari, kvartiralar va tijorat ob'ektlari savdosini xavfsiz amalga oshirishda yordam beradi. 200 dan ortiq bitimlar muvaffaqiyatli yakunlangan.",
    bioRu: "Специалист по юридическому сопровождению сделок с недвижимостью.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Toshkent Davlat Yuridik Universiteti", year: 2014 },
    ],
    expertise: ["Yer uchastkalari bitimlari", "Kadastr ishlari", "Ipoteka shartnomalari", "Mulk huquqi", "Bino qurish"],
    successRate: 85,
    availability: "available",
    tags: ["ko'chmas mulk", "yer", "ipoteka"],
  },
  {
    id: "adv-005",
    slug: "sherzod-nazarov",
    name: "Sherzod Nazarov",
    photo: "https://i.pravatar.cc/300?img=68",
    titleUz: "Mehnat huquqi va kadrlar ishlari bo'yicha yurist",
    titleRu: "Юрист по трудовому праву и кадровым вопросам",
    specialty: "labor",
    secondarySpecialties: ["corporate", "administrative"],
    region: "fergana",
    city: "Farg'ona",
    experienceYears: 7,
    licenseNumber: "ADV-2018-1024",
    rating: 4.6,
    reviewsCount: 89,
    casesResolved: 134,
    responseTimeHours: 4,
    consultationFee: { amount: 120000, currency: "UZS" },
    hourlyFee: { amount: 400000, currency: "UZS" },
    languages: ["uz", "ru"],
    verified: true,
    topRated: false,
    online: false,
    bioUz:
      "Mehnat nizolari va kadrlar hujjatlari bo'yicha professional yordam. Ish beruvchilar uchun mehnat shartnomalari, ish tavsiflari va ichki tartib qoidalarini ishlab chiqadi. Xodimlar huquqlarini himoya qilish bo'yicha 100 dan ortiq ish.",
    bioRu: "Профессиональная помощь по трудовым спорам и кадровым документам.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Farg'ona Davlat Universiteti", year: 2016 },
    ],
    expertise: ["Mehnat shartnomalari", "Ishdan bo'shatish", "Mehnat nizolari", "Kadrlar hujjatlari", "Moddiy javobgarlik"],
    successRate: 82,
    availability: "available",
    tags: ["mehnat", "kadrlar", "ish beruvchi"],
  },
  {
    id: "adv-006",
    slug: "kamola-saidova",
    name: "Kamola Saidova",
    photo: "https://i.pravatar.cc/300?img=20",
    titleUz: "Intellektual mulk va IT huquqi bo'yicha mutaxassis",
    titleRu: "Специалист по интеллектуальной собственности и IT-праву",
    specialty: "intellectual",
    secondarySpecialties: ["corporate", "international"],
    region: "tashkent-city",
    city: "Toshkent",
    experienceYears: 6,
    licenseNumber: "ADV-2019-1158",
    rating: 4.8,
    reviewsCount: 67,
    casesResolved: 89,
    responseTimeHours: 2,
    consultationFee: { amount: 280000, currency: "UZS" },
    hourlyFee: { amount: 750000, currency: "UZS" },
    languages: ["uz", "ru", "en"],
    verified: true,
    topRated: false,
    online: true,
    bioUz:
      "Intellektual mulk huquqi, dasturiy ta'minot litsenziyalash va startaplar uchun huquqiy yordam bo'yicha yosh va dinamik mutaxassis. 50 dan ortiq brend va ixtiro uchun patent olish ishlarini bajargan. IT kompaniyalar uchun TOS va NDA hujjatlarini tayyorlaydi.",
    bioRu: "Динамичный специалист по интеллектуальной собственности и IT-праву.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Westminster International University", year: 2017 },
      { degree: "Intellektual mulk huquqi magistri", institution: "WIPO Academy", year: 2019 },
    ],
    expertise: ["Patent olish", "Tovar belgilari", "Litsenziya shartnomalari", "NDA", "TOS hujjatlari", "Mualliflik huquqi"],
    successRate: 88,
    availability: "available",
    tags: ["intellektual mulk", "IT", "startap", "patent"],
  },
  {
    id: "adv-007",
    slug: "javlon-ergashev",
    name: "Javlon Ergashev",
    photo: "https://i.pravatar.cc/300?img=51",
    titleUz: "Xalqaro bitimlar va investitsiyalar bo'yicha advokat",
    titleRu: "Адвокат по международным сделкам и инвестициям",
    specialty: "international",
    secondarySpecialties: ["corporate", "tax"],
    region: "tashkent-city",
    city: "Toshkent",
    experienceYears: 16,
    licenseNumber: "ADV-2009-0287",
    rating: 4.9,
    reviewsCount: 234,
    casesResolved: 298,
    responseTimeHours: 1,
    consultationFee: { amount: 500000, currency: "UZS" },
    hourlyFee: { amount: 1500000, currency: "UZS" },
    languages: ["uz", "ru", "en"],
    verified: true,
    topRated: true,
    online: false,
    bioUz:
      "Xalqaro bitimlar va xorijiy investitsiyalar sohasidagi yetakchi ekspert. 30 dan ortiq xorijiy investorlarga O'zbekistonda biznes yuritish bo'yicha konsalting xizmatlarini ko'rsatgan. Angliya va Uels advokatlar kollejining a'zosi.",
    bioRu: "Ведущий эксперт по международным сделкам и иностранным инвестициям.",
    education: [
      { degree: "LLB", institution: "University of Cambridge", year: 2008 },
      { degree: "LLM International Business Law", institution: "London School of Economics", year: 2010 },
    ],
    expertise: ["Xalqaro shartnomalar", "Investitsiya bitimlari", "Bilateral shartnomalar", "BIT", "Xalqaro arbitraj"],
    successRate: 91,
    availability: "busy",
    tags: ["xalqaro", "investitsiya", "arbitraj", "TOP-10"],
  },
  {
    id: "adv-008",
    slug: "nigora-usmanova",
    name: "Nigora Usmanova",
    photo: "https://i.pravatar.cc/300?img=49",
    titleUz: "Ma'muriy huquq va davlat xizmatlari advokati",
    titleRu: "Адвокат по административному праву и госуслугам",
    specialty: "administrative",
    secondarySpecialties: ["civil", "tax"],
    region: "bukhara",
    city: "Buxoro",
    experienceYears: 10,
    licenseNumber: "ADV-2015-0734",
    rating: 4.7,
    reviewsCount: 143,
    casesResolved: 198,
    responseTimeHours: 3,
    consultationFee: { amount: 130000, currency: "UZS" },
    hourlyFee: { amount: 450000, currency: "UZS" },
    languages: ["uz", "ru"],
    verified: true,
    topRated: false,
    online: true,
    bioUz:
      "Davlat organlari qarorlarini shikoyat qilish, ma'muriy huquqbuzarliklar va davlat xizmatlari sohasida tajribali advokat. 150 dan ortiq fuqarolarning huquqlarini himoya qilgan. Ma'muriy sudlarda doimiy ishtirok etadi.",
    bioRu: "Опытный адвокат по административному праву и обжалованию решений госорганов.",
    education: [
      { degree: "Yuridik fanlar bakalavri", institution: "Buxoro Davlat Universiteti", year: 2013 },
    ],
    expertise: ["Ma'muriy shikoyatlar", "Davlat xizmatlari", "JARIMALAR", "Litsenziyalash", "Permitlar"],
    successRate: 84,
    availability: "available",
    tags: ["ma'muriy", "davlat xizmatlari", "shikoyat"],
  },
];

// ============================================================================
// LEGAL REQUESTS (hh.uz-style vacancy feed — clients posting needs)
// ============================================================================

export const LEGAL_REQUESTS: LegalRequest[] = [
  {
    id: "req-001",
    titleUz: "AJ ro'yxatdan o'tkazish va ustav hujjatlarini tayyorlash",
    descriptionUz:
      "Yangi qurilayotgan qurilish kompaniyasi uchun Aksiyadorlik jamiyatini ro'yxatdan o'tkazish kerak. Ustav, ta'sis shartnomasi va boshqa hujjatlar to'liq tayyorlanishi shart. Soliq maslahati ham kerak.",
    category: "corporate",
    budgetUzs: { min: 3000000, max: 5000000 },
    city: "Toshkent",
    region: "tashkent-city",
    postedAgo: "2 soat oldin",
    responsesCount: 4,
    viewsCount: 89,
    status: "open",
    clientType: "business",
    isUrgent: true,
  },
  {
    id: "req-002",
    titleUz: "Ajrashish va bolani onaga qoldirish bo'yicha yordam",
    descriptionUz:
      "Er-xotin ajrashmoqchi, 7 yoshli bola bor. Bolani onaga qoldirish va aliment undirish (er ishlaydi, rasmiy maoshi 8 mln) bo'yicha to'liq yuridik yordam kerak. Konsultatsiya va sudga tayyorlov.",
    category: "family",
    budgetUzs: { min: 1500000, max: 2500000 },
    city: "Samarqand",
    region: "samarkand",
    postedAgo: "5 soat oldin",
    responsesCount: 7,
    viewsCount: 156,
    status: "open",
    clientType: "individual",
    isUrgent: false,
  },
  {
    id: "req-003",
    titleUz: "Mehnat shartnomasini bekor qilish ustidan shikoyat",
    descriptionUz:
      "Xodimni ogohlantirishsiz va to'lovlarsiz ishdan haydagan. Mehnat kodeksining buzilgan moddalarini aniqlash, tiklanish va kompensatsiya undirish uchun da'vo arizasi tuzish kerak.",
    category: "labor",
    budgetUzs: { min: 800000, max: 1500000 },
    city: "Toshkent",
    region: "tashkent-city",
    postedAgo: "1 kun oldin",
    responsesCount: 12,
    viewsCount: 234,
    status: "open",
    clientType: "individual",
    isUrgent: false,
  },
  {
    id: "req-004",
    titleUz: "Tijorat ob'ektini ijaraga olish shartnomasini tekshirish",
    descriptionUz:
      "Restoran uchun 200 m² savdo maydonini 5 yilga ijaraga olishmoqchi. Shartnoma loyihasi tayyor, lekin qo'shimcha shartlar va xavflarni aniqlash uchun advokat tekshirishi kerak.",
    category: "real-estate",
    budgetUzs: { min: 500000, max: 1000000 },
    city: "Toshkent",
    region: "tashkent-city",
    postedAgo: "1 kun oldin",
    responsesCount: 3,
    viewsCount: 67,
    status: "open",
    clientType: "business",
    isUrgent: false,
  },
  {
    id: "req-005",
    titleUz: "Jinoyat ishi bo'yicha himoya (firibgarlik ayblovi)",
    descriptionUz:
      "Akaga nisbatan firibgarlik (162-modda) bo'yicha jinoyat ishi qo'zg'atilgan. U o'z aybini tan olmaydi. Tergov bosqichidan boshlab to'liq himoya kerak. Yaqinlari tayyorgarlik ko'rmoqda.",
    category: "criminal",
    budgetUzs: { min: 5000000, max: 10000000 },
    city: "Farg'ona",
    region: "fergana",
    postedAgo: "2 kun oldin",
    responsesCount: 5,
    viewsCount: 412,
    status: "open",
    clientType: "individual",
    isUrgent: true,
  },
  {
    id: "req-006",
    titleUz: "Brend nomi va logotip uchun tovar belgisini ro'yxatga olish",
    descriptionUz:
      "Yangi ochilayotgan kafelar tarmog'i uchun brend nomi va logotipni himoya qilish kerak. Tovar belgisini ro'yxatga olish, patent arizasini tayyorlash va to'liq huquqiy himoya.",
    category: "intellectual",
    budgetUzs: { min: 2000000, max: 3500000 },
    city: "Toshkent",
    region: "tashkent-city",
    postedAgo: "3 kun oldin",
    responsesCount: 2,
    viewsCount: 98,
    status: "open",
    clientType: "business",
    isUrgent: false,
  },
];

// ============================================================================
// TESTIMONIALS
// ============================================================================

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-001",
    authorName: "Bahrom Ilhomjonov",
    authorRoleUz: "Yuriskonsult",
    organization: "Davlat boshqaruvi akademiyasi",
    quoteUz:
      "Loyiha oddiy fuqarolar uchun juda foydali hamda qulay. Yana ko'proq hujjat namunalarini joylashtirilishini istar edim. Vaqtimni va pulimni tejadigan ajoyib tizim.",
    rating: 5,
  },
  {
    id: "test-002",
    authorName: "Olga Voytovna",
    authorRoleUz: "Yuridik bo'lim boshlig'i",
    organization: "'Ozinjenering' Respublika loyiha instituti",
    quoteUz:
      "Tizimning menga yoqqan yana bir jihati, fuqarolarning hujjatlar bilan ishlash malakasi oshadi. Huquqiy savodxonlik borasida loyiha katta amaliy maktab vazifasini o'tab beradi.",
    rating: 5,
  },
  {
    id: "test-003",
    authorName: "Xurshid Qobilovich",
    authorRoleUz: "Yuridik bo'lim boshlig'i",
    organization: "Xalq ta'limi vazirligi",
    quoteUz:
      "Fuqarolarning davlat organlariga hujjat namunasini so'rab murojaat qilishi kamayadi. Muhimi, sarsongarchiliklar ketib, vaqtdan yutiladi. Tizim davlat xizmatlarini sifatini oshiradi.",
    rating: 5,
  },
  {
    id: "test-004",
    authorName: "Madina Yusupova",
    authorRoleUz: "Tadbirkor",
    organization: "'Madina Tex' MChJ",
    quoteUz:
      "Advokat topish uchun doim tanishlarimga murojaat qilardim. Endi bir joyda barcha advokatlarni solishtirib, o'zim uchun eng maqbulini tanlay olaman. Yetkazib berish tez, narxlar aniq.",
    rating: 5,
  },
];

// ============================================================================
// STATS
// ============================================================================

export const PLATFORM_STATS = {
  advocatesCount: 1284,
  documentsCount: 697,
  requestsResolved: 8472,
  citiesCovered: 14,
  satisfactionRate: 96,
  avgResponseHours: 2,
};
